/**********************************************************************
 *
 * Copyright (C) 2010 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO GENERATED */



#ifndef FACE_LIVENESS__FILE_VERSION_H_
#define FACE_LIVENESS__FILE_VERSION_H_

#define FACE_LIVENESS_INTERNAL_NAME "FaceLiveness"

#define FACE_LIVENESS_ORIGINAL_FILENAME "aw_face_liveness.dll"
#define FACE_LIVENESS_FILE_DESCRIPTION "Aware FaceLiveness Library"

#define FACE_LIVENESS_AW_VERSION_INT 2070000

#define FACE_LIVENESS_AW_VERSION_STR "Aware FaceLiveness Library, version 2.7 r149823"

#define FACE_LIVENESS_AW_LEGAL_COPYRIGHT "Copyright (C) 2020 Aware, Inc."

#define FACE_LIVENESS_AW_EXP_CODE      97562528

#define FACE_LIVENESS_AW_EXP_DATE      00000000
#define FACE_LIVENESS_AW_EXP_TITLE     "Library Expired"
#define FACE_LIVENESS_AW_EXP_MESG      "The software tryout period has expired on %s. \nPlease Contact Aware, Inc. at (781) 276-4000"
#define FACE_LIVENESS_AW_EXP_PRODUCT   "FaceLiveness";


#endif /*FACE_LIVENESS__FILE_VERSION_H_ */
