/**********************************************************************
 *
 * Copyright (C) 2010 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO GENERATED */



#ifndef PREFACE__FILE_VERSION_H_
#define PREFACE__FILE_VERSION_H_

#define PREFACE_INTERNAL_NAME "Preface"

#define PREFACE_ORIGINAL_FILENAME "aw_preface.dll"
#define PREFACE_FILE_DESCRIPTION "Aware Preface Library"

#define PREFACE_AW_VERSION_INT 6070502

#define PREFACE_AW_VERSION_STR "Aware Preface Library, version 6.7.5.2 r146558"

#define PREFACE_AW_LEGAL_COPYRIGHT "Copyright (C) 2020 Aware, Inc."

#define PREFACE_AW_EXP_CODE      1900887652

#define PREFACE_AW_EXP_DATE      00000000
#define PREFACE_AW_EXP_TITLE     "Library Expired"
#define PREFACE_AW_EXP_MESG      "The software tryout period has expired on %s. \nPlease Contact Aware, Inc. at (781) 276-4000"
#define PREFACE_AW_EXP_PRODUCT   "Preface";


#endif /*PREFACE__FILE_VERSION_H_ */
