/**********************************************************************
 *
 * Copyright (C) 2020 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED */ 


#ifndef _AW_SCORING_ERRORS_H_
#define _AW_SCORING_ERRORS_H_

/* Error Codes */

/* No errors or warnings. */
#define AW_SCORING_E_NO_ERRORS                              0

/* The library failed to allocate memory. */
#define AW_SCORING_E_OUT_OF_MEMORY                          100

/* The scoring object was NULL. */
#define AW_SCORING_E_NULL_SCORING_OBJ                       101

/* No algorithm speeds were specified. */
#define AW_SCORING_E_NO_ALGORITHM_SPEEDS_SPECIFIED          200

/* D100 and D150 cannot both have a speed specified. */
#define AW_SCORING_E_D100_D150_MUTUALLY_EXCLUSIVE           201

/* The specified number of biometrics is not supported. */
#define AW_SCORING_E_INVALID_BIOMETRIC_COUNT                202

/* Neither D100 nor D150 had a speed specified. */
#define AW_SCORING_E_D100_OR_D150_SPEED_NOT_SPECIFIED       203

/* D350 did not have speed specified. */
#define AW_SCORING_E_D350_SPEED_NOT_SPECIFIED               204

/* D600 did not have speed specified. */
#define AW_SCORING_E_D600_SPEED_NOT_SPECIFIED               205

/* D900 did not have speed specified. */
#define AW_SCORING_E_D900_SPEED_NOT_SPECIFIED               206

/* The search time cannot be met with the specified parameters. */
#define AW_SCORING_E_SEARCH_TIME_CANNOT_BE_MET              207

/* The liveness JSON could not be parsed. */
#define AW_SCORING_E_JSON_FAILED_TO_PARSE                   300

/* The liveness JSON was missing a parameter. */
#define AW_SCORING_E_MISSING_LIVENESS_PARAMETER             301

/* The liveness JSON had a parameter with an invalid value. */
#define AW_SCORING_E_INVALID_LIVENESS_PARAMETER             302

/* A liveness decision could not be calculated. */
#define AW_SCORING_E_FAILED_TO_CALCULATE_LIVENESS           303

/* Liveness decisions are not supported in this build. */
#define AW_SCORING_E_LIVENESS_UNSUPPORTED                   304



#endif /* _AW_SCORING_ERRORS_H_ */
