/**********************************************************************
 *
 * Copyright (C) 2010 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO GENERATED */



#ifndef SCORING__FILE_VERSION_H_
#define SCORING__FILE_VERSION_H_

#define SCORING_INTERNAL_NAME "Scoring"

#define SCORING_ORIGINAL_FILENAME "aw_scoring.dll"
#define SCORING_FILE_DESCRIPTION "Aware Scoring Library"

#define SCORING_AW_VERSION_INT 1030107

#define SCORING_AW_VERSION_STR "Aware Scoring Library, version 1.3.1.7 r146621"

#define SCORING_AW_LEGAL_COPYRIGHT "Copyright (C) 2020 Aware, Inc."

#define SCORING_AW_EXP_CODE      148657923

#define SCORING_AW_EXP_DATE      00000000
#define SCORING_AW_EXP_TITLE     "Library Expired"
#define SCORING_AW_EXP_MESG      "The software tryout period has expired on %s. \nPlease Contact Aware, Inc. at (781) 276-4000"
#define SCORING_AW_EXP_PRODUCT   "Scoring";


#endif /*SCORING__FILE_VERSION_H_ */
