/**********************************************************************
 *
 * Copyright (C) 2020 Aware, Inc.
 *
 * $Workfile:  $    $Revision:  $
 * Last Modified: $Date: $ by: $Author:  $
 *
 **********************************************************************/

/* DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED */ 


#ifndef _AW_VIDEO_ERRORS_H_
#define _AW_VIDEO_ERRORS_H_

/* Error Codes */

/* No errors or warnings. */
#define AW_VIDEO_E_NO_ERRORS                                0

/* The library failed to allocate memory. */
#define AW_VIDEO_E_OUT_OF_MEMORY                            100

/* The video object was NULL. */
#define AW_VIDEO_E_NULL_VIDEO_OBJ                           101

/* Invalid camera object. */
#define AW_VIDEO_E_INVALID_CAMERA                           102

/* A function that required preview was called before preview was started. */
#define AW_VIDEO_E_PREVIEW_NOT_STARTED                      103

/* A function that required capture was called before capture was started. */
#define AW_VIDEO_E_CAPTURE_NOT_STARTED                      104

/* Problem setting up camera connection */
#define AW_VIDEO_E_GETTING_CAMERA_CONTROL                   105

/* Error getting the picture clicked using the camera. */
#define AW_VIDEO_E_GETTING_PICTURE_TAKEN_BY_CAMERA          106

/* Polling for preview image not allowed when using callback */
#define AW_VIDEO_E_PREVIEW_IS_USING_CALLBACK                107

/* Polling for captured image not allowed when using callback */
#define AW_VIDEO_E_CAPTURE_IS_USING_CALLBACK                108

/* The device disconnected */
#define AW_VIDEO_E_DEVICE_DISCONNECTED                      109

/* An invalid camera property was given. */
#define AW_VIDEO_E_INVALID_PROPERTY                         110

/* An invalid index was given for a camera property. */
#define AW_VIDEO_E_INVALID_PROPERTY_INDEX                   111

/* A function that requested a frame was called before the frame was ready. */
#define AW_VIDEO_E_FRAME_NOT_READY                          112

/* The specified results pointer was not found in this Camera. */
#define AW_VIDEO_E_INVALID_RESULTS_POINTER                  113

/* The profile specified was not a valid PreFace 6 profile. */
#define AW_VIDEO_E_INVALID_PROFILE                          114

/* The good_frame_count specified for autocapture was not high enough. */
#define AW_VIDEO_E_INVALID_AUTOCAPTURE_FRAME_COUNT          115

/* The amount of time specified was invalid. */
#define AW_VIDEO_E_INVALID_MINIMUM_TIME                     116

/* The specified minimum size is out of the range [0, 1]. */
#define AW_VIDEO_E_INVALID_MINIMUM_SIZE                     118

/* The specified maximum size is out of the range [0, 1]. */
#define AW_VIDEO_E_INVALID_MAXIMUM_SIZE                     119

/* The specified minimum size is greater than the specified maximum size. */
#define AW_VIDEO_E_INVALID_RELATIVE_SIZE                    120

/* The specified sensitivity is out of the range [0, 1]. */
#define AW_VIDEO_E_INVALID_SENSITIVITY                      121

/* The specified granularity is out of the range [0, 1]. */
#define AW_VIDEO_E_INVALID_GRANULARITY                      122

/* An invalid Algorithm type was specified. */
#define AW_VIDEO_E_INVALID_ALGORITHM                        123

/* An invalid Scoring Mode was specified. */
#define AW_VIDEO_E_INVALID_SCORING_MODE                     124

/* Interframe time must be a number greater than 0. */
#define AW_VIDEO_E_INVALID_INTERFRAME_TIME                  125

/* Interframe time must be set to complete this operation. */
#define AW_VIDEO_E_NO_INTERFRAME_TIME_SET                   126

/* Cannot change device state while capture is in progress. */
#define AW_VIDEO_E_CAPTURING                                129

/* The external camera config pointer provided was not found. */
#define AW_VIDEO_E_INVALID_EXTERNAL_CAMERA_CONFIG_POINTER   130

/* Failed to create an external camera because the external camera
   configuration object provided did not have any resolutions added. */
#define AW_VIDEO_E_EXTERNAL_CAMERA_CONFIG_NO_RESOLUTIONS    131

/* The PreFace classifier data file was not set correctly. */
#define AW_VIDEO_E_PREFACE_CLASSIFIER_DATA_FILE_NOT_SET     132

/* No profile has been specified. */
#define AW_VIDEO_E_NO_PROFILE_SPECIFIED                     133

/* The function could not complete because the connection to the Camera has
   not been opened. */
#define AW_VIDEO_E_CAMERA_NOT_OPEN                          134

/* Could not find the required DLL for extended camera functionality. */
#define AW_VIDEO_E_EXTENDED_DLL_NOT_FOUND                   135

/* The camera module required for that functionality could not be detected. 
   Please make sure all physical connections are properly plugged in to the
   camera. */
#define AW_VIDEO_E_EXTENDED_MODULE_NOT_DETECTED             136

/* The camera is busy and cannot complete the operation. */
#define AW_VIDEO_E_CAMERA_BUSY                              137

/* The camera is in an unsupported mode. */
#define AW_VIDEO_E_CAMERA_MODE_UNSUPPORTED                  138

/* The image passed into the Video Library could not be parsed for analysis. */
#define AW_VIDEO_E_PARSING_IMAGE                            139

/* The function call made is only applicable to Synchronous External
   Cameras. */
#define AW_VIDEO_E_TIMESTAMP_ONLY_APPLICABLE_TO_SYNCHRONOUS_EXTERNAL_CAMERAS 140

/* The value for the timestamp provided was invalid.  Timestamps must be
   greater than the previous timestamp and greater than or equal to 0.00
   seconds. */
#define AW_VIDEO_E_INVALID_TIMESTAMP                        141

/* The camera has failed to capture a valid image during the capture
   process. */
#define AW_VIDEO_E_CAPTURE_FAILED                           142

/* The Algorithm specified does not accept scores from outside sources. */
#define AW_VIDEO_E_ALGORITHM_DOES_NOT_ACCEPT_SCORES         143

/* The Algorithm specified is not enabled. */
#define AW_VIDEO_E_ALGORITHM_NOT_ENABLED                    144

/* The Algorithm specified is not supported on this device. */
#define AW_VIDEO_E_ALGORITHM_NOT_SUPPORTED                  145

/* The Algorithm specified does not use a model file. */
#define AW_VIDEO_E_ALGORITHM_DOES_NOT_USE_MODEL             146

/* The Algorithm specified failed to load the model file. */
#define AW_VIDEO_E_ALGORITHM_FAILED_TO_LOAD_MODEL           147

/* The underlying camera device driver is out of date. */
#define AW_VIDEO_E_DEVICE_DRIVER_OUT_OF_DATE                150

/* Cannot refresh the camera list while there are any cameras open. */
#define AW_VIDEO_E_REFRESH_FAILED_CAMERA_OPEN               151

/* The image format specified is invalid. */
#define AW_VIDEO_E_INVALID_IMAGE_FORMAT                     152

/* The image submitted to the External Camera for analysis does not match
   the current preview resolution. */
#define AW_VIDEO_E_RESOLUTION_MISMATCH                      153

/* Invalid stream object. */
#define AW_VIDEO_E_INVALID_STREAM                           300

/* The preview resolution specified is larger than the capture resolution. */
#define AW_VIDEO_E_PREVIEW_LARGER_THAN_CAPTURE              301

/* The rotation angle must be 0, 90, 180, or 270. */
#define AW_VIDEO_E_INVALID_ROTATION_ANGLE                   312

/* Property being manipulated does not apply to the selected device */
#define AW_VIDEO_E_PROPERTY_NOT_APPLICABLE_TO_DEVICE        410

/* The function call made or its parameters are not supported in Mobile
   mode. */
#define AW_VIDEO_E_UNSUPPORTED_IN_MOBILE_MODE               411

/* The version of Preface loaded does not match the version of the Video
   Library being used. */
#define AW_VIDEO_E_PREFACE_VERSION_MISMATCH                 998

/* The function called is not supported for the operating system being run. */
#define AW_VIDEO_E_FUNCTION_NOT_SUPPORTED_FOR_OS            999

/* Failed to parse the JSON request. */
#define AW_VIDEO_E_FAILED_TO_PARSE_JSON                     10001

/* The function name was not valid. */
#define AW_VIDEO_E_INVALID_FUNCTION_NAME                    10002

/* The parameter list must be a JSON array. */
#define AW_VIDEO_E_INVALID_PARAMETER_LIST                   10003

/* A parameter had an incorrect type. */
#define AW_VIDEO_E_INVALID_PARAMETER_TYPE                   10004

/* The wrong number of parameters were passed to the function. */
#define AW_VIDEO_E_INCORRECT_PARAMETER_COUNT                10005

/* The channel name is incorrect, hasn't been opened, or is closed. */
#define AW_VIDEO_E_INVALID_CHANNEL_NAME                     10006



#endif /* _AW_VIDEO_ERRORS_H_ */
